README.rst
Might as well use the issue tracker on GH if the repo is going to be hosted here.
=> Don't link to bugs.python.org

README.rst, performance/benchmarks/__init__.py, performance/benchmarks/bm_regex_dna.py
Patch written by Serhiy Storchaka: http://bugs.python.org/issue26436
It seems like Pyston has the same benchmark with minor changes:
* https://github.com/dropbox/pyston-perf/blob/master/benchmarking/benchmark_suite/fasta.py
* Pyston benchmark is called "fasta"
* fasta replaces stdout to check the output
* fasta moved the LCG RNG to a genRandom() subfunction which is a good idea to make random_fasta() more readable. Since it's only used to initialize the benchmark, it has no impact on performance.
* probably other subtle differences, I didn't check carefully
=> Add regex_dna benchmark

README.rst
The option --with-optimization was renamed to --enable-optimizations, see https://bugs.python.org/issue26359#msg281301
=> Rename --with-optimization to --enable-optimizations

doc/changelog.rst, performance/benchmarks/bm_logging.py
I just saw that `warn` is deprecated and all tests passes with tox, thus sent a PR,but it might be inappropriate if there are other compatibility issues.
=> changes warn to warning

performance/benchmarks/bm_pickle.py
change the logic to detect/use c-accelerators for pickle when using PyPy for python 3.5 (called PyPy3 by the PyPy people)
=> COMPAT: PyPy does not have c-accelerators for pickle

performance/benchmarks/bm_python_startup.py
Python 3 has more graceful shutdown process.
It is one of major reason why Python 3 is slower than
python_startup benchmark.
But shutdown time is not important as startup time
for applications like Vim.
And user can avoid shutdown process, while startup
overhead is unavoidable.
New `--exit` option calls `os._exit(0)` to avoid
shutdown process.  Pure startup time can be measured
by this option.
=> python_startup: Add --exit option

AUTHORS, doc/benchmark.conf.sample, performance/compile.py
At least on macOS, installing up-to-date versions of several libraries
via a third party package manager such as Homebrew may interfere with
the rather old and tired version shipped with macOS. Consequently,
Homebrew does not add these libraries to the include and linker paths.
This change adds a configuration option to derive the correct arguments
for CPython's configure script. Adding support for other package
managers and operating systems should be trivial, since only two lines
are macOS-specific.
=> Add support for native libraries that are installed but not on path

doc/benchmarks.rst
It seems that group has been removed, let's not mention it anymore.
=> doc: remove mention of removed threading group

.travis.yml
The sudo keyword is now ignored.
See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
=> sudo no longer required

pyperformance/benchmarks/bm_tornado_http.py
Python 3.8 changed the default event loop to ProactorEventLoop which doesn't
implement everything required by tornado and breaks the benchmark.
This makes WindowsSelectorEventLoop the default again like suggested in:
tornadoweb/tornado#2686
Limit to 3.8 only in the hopes that the new event loop supports the required
methods with 3.9.
Fixes #61
=> tornado: use WindowsSelectorEventLoopPolicy() with Python 3.8

pyperformance/requirements.txt
The last release allows mako to run on Windows with Python 3.8, see
https://github.com/sqlalchemy/mako/issues/301 for details
Fixes #63
=> Update mako to 1.1.0 for Python 3.8 on Windows fixes

pyperformance/cli.py, pyperformance/cli_run.py
I wanted to run pyperformance benchmark with another executable, while using a venv for the pyperformance and benchmark packages. I had to make these changes to get it to work.
=> Enable running with alternative python, inside venv

pyperformance/benchmarks/__init__.py, setup.py
=> Skip the genshi benchkmark as it fails with 3.11

pyperformance/benchmarks/__init__.py
It looks like it was missed in [this commit](https://github.com/python/pyperformance/commit/b92f635c96b080982a71a106c1ee20ef7e0cbc00).
This was discovered while performance testing a build of python that didn't have `_sqlite3` built, and so when running the following:
```
python -m pyperformance run --benchmarks=-sqlalchemy_declarative,-sqlalchemy_imperative,-sqlite_synth
```
One gets a KeyError on `func = bench_funcs[name]` in `run.py`, and trying to work around it (adding `-html5lib` to `--benchmarks`) doesn't work, because `__init__.py` assumes things are in a consistent state.
=> Remove comment disabling BM_html5lib function

MANIFEST.in, pyperformance/__init__.py, pyperformance/cli.py, pyperformance/tests/test_compare.py, pyperformance/venv.py
(for #120)
In some cases the wrong files were getting installed.
Also, running from a development env (AKA, git checkout) causes pyperformance to get installed into a venv.  However, pip treats this as a "develop" install and the venv basically has a link back to the original files (rather than making a copy).  This lead to incorrect logic when detecting "is installed"
Both issues are resolved here.
=> Fix non-devel installs.

pyperformance/data-files/benchmarks/bm_genshi/requirements.txt, pyperformance/data-files/benchmarks/bm_sqlalchemy_declarative/requirements.txt, pyperformance/data-files/benchmarks/bm_sqlalchemy_imperative/requirements.txt, setup.py
Update the pinned versions of `genshi` and `greenlet` to recent ones that work on all branch heads. Fixes #113.
=> Fix CPython 3.11 failures

pyperformance/_pythoninfo.py
=> Fix the "is dev?" logic in inspect_python_install()

.gitignore, MANIFEST.in, dev.py, pyperformance/__init__.py, pyperformance/cli.py, pyperformance/compile.py, pyperformance/run.py, pyperformance/tests/__init__.py, pyperformance/tests/test_pythoninfo.py, pyperformance/tests/test_show.py, pyperformance/venv.py, runtests.py
A number of things get simpler if we require pyperformance to always be installed.  In particular, we no longer need to create a top-level venv all the time.
This change also includes a convenience script, dev.py, to create a venv if needed.
=> Require pyperformance to be installed before running

pyperformance/tests/test_commands.py, runtests.py
We have been ignoring the exit code of the subprocess in runtests.py.
=> Preserve the Exit Code of Running the Tests

pyperformance/_pip.py, pyperformance/venv.py
(see #148)
pyperf treats psutil as an optional dependency.  Most of the time it should be installable, but we weren't really even trying.  This PR fixes that.
=> Always Try to Install psutil

pyperformance/data-files/benchmarks/bm_fannkuch/run_benchmark.py
Not sure what the philosophy on changes to the benchmarks themselves is in this repo; the theory of this PR is that the benchmarks are intended to be reasonable representations of the most efficient way to accomplish a given (admittedly meaningless) task in Python with the correct result, and it doesn't make sense to have pure wasted work in the benchmarks.
This `check` var is initialized and incremented, but never used, and plays no role in returning the correct result.
=> Remove unused var from fannkuch

pyperformance/data-files/benchmarks/bm_genshi/requirements.txt
Instead of a direct github URL.
See https://github.com/edgewall/genshi/issues/66#issuecomment-1105149926
=> Genshi 0.7.7 is released, use it

.github/workflows/main.yml
Current GitHub Action only executes the default PyPy version of Ubuntu which is actually 3.6 and too old but we are executing the CI for CPython 3.[7-10].
We may need to expand the PyPy version to support their latest implementation and match the identical versions.
=> github: Update PyPy version from 3.6 to [3.7, 3.8, 3.9]

pyperformance/_manifest.py, pyperformance/cli.py
Previously they would show up as conflicts on the "group" section
=> Add support for multiple benchmark groups in a manifest

doc/benchmarks.rst, pyperformance/data-files/benchmarks/MANIFEST, pyperformance/data-files/benchmarks/bm_deepcopy/pyproject.toml, pyperformance/data-files/benchmarks/bm_deepcopy/run_benchmark.py
One python method that is currently not in the pyperformance benchmarks is `deepcopy`. This PRs adds a benchmark that tests performance of `deepcopy` on a nested dictionary and a dataclass.
The dictionary and dataclass have been chosen as example of structures can are often copied and then modified. (e.g. passing configuration settings to a method that modifies one of the settings before passing it on)
Fixes #199
=> Add benchmark for deepcopy

pyperformance/data-files/benchmarks/MANIFEST, pyperformance/data-files/benchmarks/bm_coroutines/pyproject.toml, pyperformance/data-files/benchmarks/bm_coroutines/run_benchmark.py, pyperformance/data-files/benchmarks/bm_generators/run_benchmark.py
- Add a benchmark for coroutines
Benchmark results:
| Benchmark      | 3.10    | 3.12                  |
|----------------|:-------:|:---------------------:|
| coroutines     | 47.1 ms | 34.8 ms: 1.35x faster |
=> Add coroutines benchmark

pyperformance/data-files/benchmarks/MANIFEST
When the `mdp` benchmark was [added](https://github.com/python/pyperformance/pull/14) over 5 years ago, it was disabled by default because it took too long to run (reportedly 7-8 seconds).
However, this situation has improved somewhat (I time about 3 seconds on recent Python versions), and we're currently trying to move towards including more long-running benchmarks in the default suite.
It's a good benchmark, so let's enable it again.
=> Add `mdp` back into the `default` group

pyperformance/data-files/benchmarks/bm_raytrace/run_benchmark.py
`array.tostring` was replaced with `array.tobytes` by Python 3.2.
`array.tostring` does not work anymore and this feature was broken for many years :(
ref: https://docs.python.org/3/library/array.html#array.array.tobytes
=> Fix bm_raytrace filename option

pyperformance/_manifest.py
We weren't properly resetting `_resolve` when switching between files.  So if the default manifest came first in a "combined" manifest, any includes or benchmarks after that would erroneously use the default `resolve_default_benchmark()`.
=> Ensure We Use the Right _resolve()

pyperformance/_manifest.py, pyperformance/cli.py, pyperformance/commands.py
This addresses several of the problems noted in #234.
Notably:
* disallow groups named "all"
* disallow duplicate group names, even if in different included manifests
* disallow benchmarks named "all"
* disallow duplicate benchmark names
* clean up the "list_groups" command
* fix how group resolution falls back to the tags
=> Fix Manifest Group

pyperformance/data-files/benchmarks/MANIFEST, pyperformance/data-files/benchmarks/bm_async_generators/pyproject.toml, pyperformance/data-files/benchmarks/bm_async_generators/run_benchmark.py
```console 
3.10 -> async_generators: Mean +- std dev: 643 ms +- 28 ms
main -> async_generators: Mean +- std dev: 441 ms +- 20 ms
```
=> add async_generators benchmark

pyperformance/data-files/benchmarks/MANIFEST, pyperformance/data-files/benchmarks/bm_dask/pyproject.toml, pyperformance/data-files/benchmarks/bm_dask/requirements.txt, pyperformance/data-files/benchmarks/bm_dask/run_benchmark.py
The Dask scheduler is largely pure-python-code-bound.  There is a [discussion about the details here](https://github.com/dask/distributed/issues/854).  For this reason, it makes a good real-world workload of a distributed system benchmark (even when the benchmark is running locally on a single core).
Thanks to @TomAugspurger for the suggestion, and @mrocklin for providing the meat of the benchmark itself.
=> Add a Dask benchmark

pyperformance/data-files/benchmarks/bm_django_template/requirements.txt, pyperformance/data-files/benchmarks/bm_sympy/requirements.txt
Fixes #247.
Django has a runtime dependency on distutils, so adding setuptools as a dependency resolves it.
This has already been resolved upstream [1], but this allows us to keep using the same version of Django for the benchmark.
[1] https://github.com/django/django/pull/14240/files
=> Fix the django_template benchmark on cpython main

.github/workflows/publish.yml, pyproject.toml
* Enable easier release process, we already use the same process for the pyperf releasing.
=> .github: Add Automated release process

pyperformance/data-files/benchmarks/MANIFEST, pyperformance/data-files/benchmarks/bm_asyncio_tcp/pyproject.toml, pyperformance/data-files/benchmarks/bm_asyncio_tcp/run_benchmark.py
From https://github.com/python/cpython/issues/91166
We can show off this optimization as part of 3.12 performance improvement :)
=> Add `asyncio_tcp` benchmark

pyperformance/data-files/benchmarks/MANIFEST, pyperformance/data-files/benchmarks/bm_comprehensions/pyproject.toml, pyperformance/data-files/benchmarks/bm_comprehensions/run_benchmark.py
This benchmark is loosely based on real code in an internal workload where it makes heaviest use of list comprehensions, obviously simplified and anonymized.
=> add comprehensions benchmark

.github/workflows/main.yml
Until the `Resource not accessible by integration` is resolved, let's opt-out of the detection bit.
=> gh-263: Remove detection bit for a while

.github/workflows/main.yml
This will fix some deprecation warnings in the CI summary, for example https://github.com/python/pyperformance/actions/runs/4704880322:
> ubuntu-latest - 3.10
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
=> Bump GitHub Actions

pyperformance/data-files/benchmarks/MANIFEST, pyperformance/data-files/benchmarks/bm_richards_super/pyproject.toml, pyperformance/data-files/benchmarks/bm_richards_super/run_benchmark.py
Currently, none of the benchmarks in pyperformance exercise `super()` method calls significantly. But real-world modern object-oriented Python code often does (one source: Instagram server codebase uses lots of `super()` method calls, some in hot paths.)
To correct this gap in visibility, this PR adds a copy of the Richards benchmark that is modified to use `super()` calls. Existing super-method calls that were done by naming the base class directly (`Task.__init__(self, ...)`) are modified to use `super()`, and the already-polymorphic `Task.fn` method is modified slightly such that overrides now call up to the base method using `super()`.
If we accept that Richards is a roughly reasonable representation of some object-oriented Python code, I think this is a similarly reasonable …
=> add version of Richards that uses super()

pyperformance/data-files/benchmarks/MANIFEST, pyperformance/data-files/benchmarks/bm_typing_runtime_protocols/pyproject.toml, pyperformance/data-files/benchmarks/bm_typing_runtime_protocols/run_benchmark.py
We had a longstanding issue open at CPython complaining that the performance of `isinstance()` checks against runtime-checkable protocols was a serious bottleneck for their programme. The performance of these `isinstance()` checks has been significantly improved for 3.12 compared to 3.11, but there's currently no code (to my knowledge) in pyperformance that significantly exercises `isinstance()` checks against runtime-checkable protocols.
Work towards #105.
=> Add a benchmark for runtime-checkable protocols

.github/workflows/main.yml
I'm currently getting a daily email informing me that the pyperformance tests failed on the `AlexWaygood/pyperformance` repo (because I enabled workflows for my fork). This PR makes it so that the `test` workflow only happens on `python/pyperformance`, not on contributors' forks of the repo (unless they specifically request the workflow by manually triggering the workflow or by making a PR to their fork).
We use a condition like this in our typeshed workflow here, and it works great: https://github.com/python/typeshed/blob/ae0c9f9dadd72ee823d289416943a9109e24fe52/.github/workflows/daily.yml#L33
=> Don't run the daily test on contributors' GitHub forks

pyperformance/venv.py
The `--inherit-environ` flag was only inconsistently supported; it had no effect in case we were reusing an existing venv.
=> support --inherit-environ when reusing a venv

MANIFEST.in
The `asyncio_tcp_ssl` benchmark currently fails when it's run on an installed pyperformance, because the cert files it depends on are not installed.
This updates the `MANIFEST.in` so they are installed.
```
2023-05-07T01:58:11.2528043Z   File "/home/benchmarking/actions-runner/_work/benchmarking/benchmarking/cpython/Lib/asyncio/runners.py", line 194, in run
2023-05-07T01:58:11.2528559Z     return runner.run(main)
2023-05-07T01:58:11.2528859Z            ^^^^^^^^^^^^^^^^
2023-05-07T01:58:11.2529594Z   File "/home/benchmarking/actions-runner/_work/benchmarking/benchmarking/cpython/Lib/asyncio/runners.py", line 118, in run
2023-05-07T01:58:11.2530148Z     return self._loop.run_until_complete(task)
2023-05-07T01:58:11.2530507Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
=> Include cert files for asyncio_tcp_ssl benchmark

doc/benchmarks.rst, pyperformance/data-files/benchmarks/MANIFEST, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_cpu_io_mixed.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_eager.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_eager_cpu_io_mixed.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_eager_io.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_eager_memoization.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_io.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_memoization.toml, pyperformance/data-files/benchmarks/bm_async_tree/run_benchmark.py
goes along with https://github.com/python/cpython/issues/97696 (implemented in https://github.com/python/cpython/pull/102853)
this change to pyperformance was used to measure the impact of the eager task execution feature.
=> Extend async tree benchmarks to cover eager task execution

pyperformance/data-files/benchmarks/bm_django_template/requirements.txt, pyperformance/data-files/benchmarks/bm_sympy/requirements.txt
pyperformance will always install setuptools anyway, and specifying the version here installs a version that is too old and breaks on current Python 3.12
=> Don't specify setuptools as a dependency

pyperformance/_pyproject_toml.py
I found this issue while I am working on gh-294.
=> gh-294: Fix typo of str.partition from _pyproject_toml.py

pyperformance/data-files/benchmarks/bm_tornado_http/requirements.txt
Reverts python/pyperformance#297
Apologies, I should't have merged https://github.com/python/pyperformance/pull/297 because we only want to bump the non-benchmark dependencies:
* https://github.com/python/pyperformance/pull/296
* https://github.com/python/pyperformance/issues/223
=> Revert "Bump tornado from 6.1 to 6.3.2 in /pyperformance/data-files/benchmarks/bm_tornado_http"

pyperformance/data-files/benchmarks/MANIFEST, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_cpu_io_mixed_tg.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_eager.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_eager_cpu_io_mixed.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_eager_cpu_io_mixed_tg.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_eager_io.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_eager_io_tg.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_eager_memoization.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_eager_memoization_tg.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_eager_tg.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_io_tg.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_memoization_tg.toml, pyperformance/data-files/benchmarks/bm_async_tree/bm_async_tree_tg.toml, pyperformance/data-files/benchmarks/bm_async_tree/pyproject.toml, pyperformance/data-files/benchmarks/bm_async_tree/run_benchmark.py
This PR adds 8 new async_tree benchmark variants covering TaskGroups usage for the 8 original variants.
In addition, I also added asyncio tags to all these benchmarks, and added a requires-python field to restrict the TaskGroups variants to >=3.11 and the eager variants to >=3.12.
fixed gh-287
=> gh-287: Add TaskGroups variants to async_tree benchmarks

.github/workflows/publish.yml
This means we don't need a long-lived token stored in this repo:
* https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
* https://docs.pypi.org/trusted-publishers/using-a-publisher/
Needs an admin to log in to https://pypi.org/manage/project/pyperformance/settings/publishing/ and add a new publisher:
After that, we can delete `PYPI_API_TOKEN` from this repo's secrets and also the corresponding one at https://pypi.org/manage/account/ for whoever set it up.
=> Publish to PyPI using a trusted publisher

.github/dependabot.yml
Follow on from https://github.com/python/pyperformance/pull/296, we need to set a `schedule.interval`:
https://github.com/python/pyperformance/pull/296#issuecomment-1571564661
Monthly works well in our other repos:
```console
❯ rg "  interval: " -t yaml
output/python/bedevere/.github/dependabot.yml
7:      interval: monthly
16:      interval: monthly
output/python/miss-islington/.github/dependabot.yml
6:    interval: monthly
14:    interval: monthly
output/python/cpython/.github/dependabot.yml
6:      interval: "monthly"
output/python/blurb_it/.github/dependabot.yml
6:    interval: monthly
output/python/devguide/.github/dependabot.yml
6:    interval: monthly
output/python/cherry-picker/.github/dependabot.yml
6:    interval: monthly
```
=> Set a dependabot schedule interval

pyperformance/cli.py, pyperformance/run.py
The user can now control the minimum time a benchmark should run directly from the CLI via --min-time which then is passed to pyperf.
=> Expose --min-time from pyperf to pyperformance CLI

pyperformance/data-files/benchmarks/bm_coverage/requirements.txt
In https://discuss.python.org/t/about-speed-python-org-and-aarch64/22519/9?u=hugovk, @diegorusso discovered coverage.py 6.4.1 and 7.3.1 fail to build its ctracer for Python 3.13, meaning it uses the Python version instead of the C version, which is much slower.
However, coverage.py 7.3.2 works for Python 3.13.
---
What's the policy around bumping dependencies of benchmarks?
Do we minimise them to keep results stable?
In this case, it seems necessary to update.
=> Bump coverage to 7.3.2 for compatibility with Python 3.13

.github/workflows/main.yml, pyperformance/data-files/benchmarks/bm_sqlalchemy_declarative/requirements.txt, pyperformance/data-files/benchmarks/bm_sqlalchemy_imperative/requirements.txt
* Add CPython 3.13 as the experimental CI
* Upgrade greenlet to 3.0.0-rc3
* Update CPython 3.12 as the non-experimental CI
* Remove Python 3.7 from the CI (EOL)
* Set 3.12 default CPython version for other platforms
=> Add experimental CI for CPython 3.13

pyperformance/requirements/requirements.txt
This is to get [this bugfix](https://github.com/psf/pyperf/pull/170), that pystats weren't collected during warmups, and therefore we were missing some stats about specializations and optimizations.
=> Upgrade to pyperf 2.6.2

doc/benchmark.conf.sample
Currently it's at the wrong location and doesn't actually do anything.
=> Move jobs to correct location in benchmark.conf.sample

pyperformance/requirements/requirements.txt
See: https://github.com/python/cpython/issues/116024
Except for coverge.py related benchmarks, pyperformance is runnable from a free-threaded build.
cc @colesbury
=> Upgrade to pyperf 2.6.3

pyperformance/data-files/benchmarks/bm_dask/run_benchmark.py
The [dask benchmark hangs indefinitely on Python 3.13 on Windows](https://github.com/python/cpython/issues/118715).  This will just raise an exception instead to fix the benchmark.
There is already [a fix for this bug in dask here](https://github.com/dask/distributed/commit/e4a054505f1d584d920d6d1df2c419074de45d05), however, until that is released, we should guard against it so the benchmark suite doesn't hang on Windows.
=> Skip dask benchmark on Windows for Python 3.13

doc/usage.rst
In the previous version, the document gave an example on how to compare Python 3.6 and Python 3.7 performance. However, the commands in the example referred partially to Python 3.8. Since this is confusing and not inline with the first line of the section, I changed the example so that it fits the text.
=> Fix mentioned Python versions to headline

.github/workflows/main.yml
reference: https://dev.to/hugovk/help-us-test-free-threaded-python-without-the-gil-1hgf
=> no-issue: Add free-threading CI

pyperformance/cli.py
This might be quite niche, but I actually wanted to check the version I just installed using the CLI and I was surprised that there was no option for that. I used the same convention as for the python version `python -V` (although I did not support the `-VV` variant).
=> feat: add `-V/--version` CLI option

pyperformance/data-files/benchmarks/bm_decimal_factorial/pyproject.toml, pyperformance/data-files/benchmarks/bm_decimal_factorial/run_benchmark.py, pyperformance/data-files/benchmarks/bm_decimal_pi/pyproject.toml, pyperformance/data-files/benchmarks/bm_decimal_pi/run_benchmark.py
These currently exist in the [CPython source](https://github.com/python/cpython/blob/main/Modules/_decimal/tests/bench.py), but it would be good to have them here for continuous benchmarking.
=> Add benchmarks for the decimal module

pyperformance/run.py
When running multiple benchmarks, pyperformance first creates a venv with the dependencies for each benchmark.  More specifically, it actually first tries to install the dependencies into a "global" venv (to reduce the number of total venvs created), and if that fails installs into a new venv specific to the benchmark.  If something is broken in one of the dependencies (usually it's because upstream CPython broke backward compatibility on purpose and the dependency no longer compiles), it fails on both attempts, and pyperformance just moves along to the next benchmark.
However, a recent change to `setuptools` now leaves the package cache in a bad state on the first attempt such that installing `wheel` on the second attempt fails.  This creates an exception where one wasn't expected and …
=> Don't fail entirely when can't install requirements for a specific benchmark

.github/workflows/main.yml, .github/workflows/mypy.yml, .github/workflows/publish.yml, pyproject.toml
Python 3.8 is end-of-life next month:
* https://devguide.python.org/versions/
* https://peps.python.org/pep-0569/#lifespan
Many of the files under `pyperformance/data-files/benchmarks/` have `requires-python = ">=3.7"` or `requires-python = ">=3.8"` but I've not changed them.
=> Drop support for Python 3.7 and 3.8

pyperformance/data-files/benchmarks/bm_async_tree/run_benchmark.py
Since https://github.com/python/cpython/pull/124899, argparse help strings are more strict, and will fail with invalid `%` format strings.
=> Fix a docstring in async_tree benchmark

doc/usage.rst, pyperformance/cli.py, pyperformance/run.py, pyperformance/tests/test_commands.py
This is follow-on work to [supporting hooks in pyperf](https://github.com/psf/pyperf/pull/193), and simply allows specifying hooks to run from pyperformance.
=> Support specifying hooks in pyperformance

.github/workflows/main.yml, doc/changelog.rst, pyperformance/data-files/benchmarks/bm_asyncio_websockets/run_benchmark.py, pyperformance/data-files/benchmarks/bm_bpe_tokeniser/run_benchmark.py, pyperformance/data-files/benchmarks/bm_dask/pyproject.toml, pyperformance/data-files/benchmarks/bm_dask/requirements.txt, pyperformance/data-files/benchmarks/bm_dask/run_benchmark.py, pyperformance/data-files/benchmarks/bm_tornado_http/requirements.txt
This also fixes various things about the benchmarks so the unit tests pass on Windows.
=> Make Windows a non-experimental platform in CI

.github/workflows/main.yml
See: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/ and https://github.com/psf/pyperf/pull/212
=> .github: Add ARM64 CI

pyperformance/run.py
Fix --same-loops handling so it doesn't accumulate --loops arguments in subsequent pyperf args.
=> Fix --same-loops handling

pyperformance/cli.py, pyperformance/run.py
When running pystats collection, it is useful to /not/ do warmup runs so we don't "miss" any of the stats.  This requires being able pass the `--warmups` argument to the underlying pyperf.
=> Pass --warmup along to pyperf
