- performance/venv.py
This is the issue specifically: https://bugs.python.org/issue19124
This is also mentioned by Brett in #5
> Change execv to Popen to avoid cmd backgrounding issue in windows.

- README.rst
- TODO.rst
- performance/benchmarks/__init__.py
- performance/benchmarks/bm_mdp.py
Code comes from PyPy benchmarks:
https://bitbucket.org/pypy/benchmarks/src/59290b59a24e54057d4c694fa4f47e7879a347a0/own/bm_mdp.py?at=default&fileviewer=file-view-default
Changes:
- Reformat using autopep8
- Port to Python 3: replace zip()[0] with list(zip())[0]
- Remove dead code like tarjanSCC()
- Use the perf module to run the benchmark
> Add MDP benchmark

- doc/benchmarks.rst
- doc/changelog.rst
- performance/benchmarks/bm_logging.py
Revert partially commit b22d38d0f76ed21152e146fec3fa65f76da1372b.
> Add again logging_silent benchmark

- performance/compile.py
On my firewalled box, the only way for pip to succeed is by having the the http_proxy / https_proxy environment variables set properly. Unfortunately, --inherit-environ option wasn't working as expected. The command I used was:
./pyperformance compile --inherit-environ=http_proxy,https_proxy benchmark.conf $mybranch
This would eventually invoke pip without the http_proxy/https_proxy environment variables set, causing it to timeout and fail. This commit fixes the problem.
Feel free to modify, and I will test it again on my side.
> Inherit the environment in recursive invocations

- performance/benchmarks/bm_tornado_http.py
- performance/requirements.txt
> Upgrade tornado to 5.1.1

- performance/compile.py
> Update compile.py for Mac OS

- performance/benchmarks/__init__.py
- performance/benchmarks/bm_tornado_http.py
> fix bm_tornado_http

- README.rst
This is mostly to test if CI works for PRs.
> README: Add an appveyor status badge

- .travis.yml
- tox.ini
Drop CPython 2.7 support and replace pypy with pypy3.
> Travis, tox: drop Python 2 support

- .travis.yml
Also replace Python 3.7 with 3.6
> Travis CI: add Python 3.9

- doc/benchmark.conf.sample
> Add an example for compile_all_revisions

- pyperformance/benchmarks/bm_pickle.py
closes: https://github.com/python/pyperformance/issues/96
> bm_pickle: Rename is_module_accelerated to is_accelerated_module

- MANIFEST.in
> Include `requirements.txt` of benchmarks.

- pyperformance/_pythoninfo.py
- pyperformance/run.py
- pyperformance/tests/test_pythoninfo.py
- pyperformance/venv.py
This is a step toward simplifying the venv code, to make it easier to create fewer venvs (and update existing ones less frequently).  This change doesn't change any behavior.  It is mostly moving things around, i.e. setup, for later PRs.
> Add _pythoninfo.PythonInfo

- pyperformance/_python.py
- pyperformance/_pythoninfo.py
- pyperformance/run.py
- pyperformance/tests/__init__.py
- pyperformance/tests/test_python.py
- pyperformance/tests/test_pythoninfo.py
- pyperformance/tests/test_venv.py
- pyperformance/venv.py
This undoes some of the excess in my last PR.
> Simplify _pythoninfo.py

- pyperformance/_benchmark.py
- pyperformance/_pip.py
- pyperformance/_utils.py
- pyperformance/_venv.py
- pyperformance/compile.py
- pyperformance/run.py
- pyperformance/tests/test_venv.py
- pyperformance/venv.py
This also includes some small fixes.
> Further venv-related Cleanup

- pyperformance/_pip.py
- pyperformance/_venv.py
- pyperformance/run.py
- pyperformance/venv.py
This also includes a few small fixes.
> Share a venv, if possible

- doc/usage.rst
Leaving this PR as a sign that I'm working on this.
See #177.
> Update usage docs

- .github/workflows/main.yml
- pyperformance/commands.py
- pyperformance/compare.py
- pyperformance/tests/__init__.py
- pyperformance/tests/test_commands.py
- pyperformance/venv.py
> Get the Full Test Suite Running on PRs for Windows

- pyperformance/tests/test_pythoninfo.py
> Fix the pythoninfo Tests

- pyperformance/compile.py
We were trying to install pyperformance from the wrong directory.
> Fix the compile Command

- pyperformance/_benchmark.py
Problem initially appeared [here](https://github.com/python/pyperformance/issues/139). Solution introduced [here](https://github.com/python/pyperformance/pull/140), but was later requested to be split from that PR's main focus.
> Fix --inherit-environ issue

- pyperformance/_manifest.py
in manifest group sections
fixes #191
> Treat non +- lines as positive

- pyperformance/_benchmark.py
- pyperformance/_benchmark_metadata.py
- pyperformance/data-files/requirements.txt
- pyperformance/run.py
This requires the following changes to pyperf first: https://github.com/psf/pyperf/pull/132
> Support reporting geometric mean by tags

- pyperformance/compile.py
Currently, if a single benchmark fails, none of the results are uploaded for that entire `compile` command run.  With this change, we always upload the results if only individual benchmarks fail.  If the compilation fails or "global" venv building fails, of course, we still don't upload.
This changes the reporting for `compile_all`: Since uploading now almost always happens, there's no reason to report it as a special case.  Instead, we note when it fails as a result of a benchmark failing, and report that some benchmarks didn't work for that run.
Testing this is really tricky, given that we don't have any tests at all that capture and check the output of `compile` or `compile_all` currently.  I'm not sure it's worth the effort to clean that up as part of this specific PR.
I did manually …
> Fix #214: Always upload, even when some benchmarks fail

- doc/benchmark.conf.sample
- pyperformance/compile.py
For reduce compilation time cost in multi core machines.
> Add jobs field in compile section to specify make -j param

- .github/workflows/main.yml
Makes it easier to debug CI issues without creating a PR
> Allow contributors to manually run tests on their GitHub forks

- doc/benchmarks.rst
Link is dead, added archived link of the article.
> Fixed broken link  benchmarks.rst

- .github/workflows/main.yml
I like the improved suggestion from https://github.com/psf/pyperf/pull/189
> no-issue: Improve CI for free-threading

- pyperformance/tests/data/find-pyperformance.py
- tox.ini
In order to run tox and make, config files need to updated.
> Update configuration files
